{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7f178bb8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting gspread\n",
      "  Downloading gspread-6.2.1-py3-none-any.whl (59 kB)\n",
      "\u001b[K     |████████████████████████████████| 59 kB 5.8 MB/s eta 0:00:011\n",
      "\u001b[?25hCollecting oauth2client\n",
      "  Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)\n",
      "\u001b[K     |████████████████████████████████| 98 kB 8.1 MB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting streamlit\n",
      "  Downloading streamlit-1.40.1-py2.py3-none-any.whl (8.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 8.6 MB 44.6 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: pandas in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (1.2.4)\n",
      "Requirement already satisfied: google-auth>=1.12.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from gspread) (2.6.2)\n",
      "Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from gspread) (0.4.6)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (5.0.0)\n",
      "Requirement already satisfied: six>=1.9.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (1.15.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (0.2.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from google-auth>=1.12.0->gspread) (4.8)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from google-auth-oauthlib>=0.4.1->gspread) (1.3.1)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.4.8)\n",
      "Requirement already satisfied: requests>=2.0.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.25.1)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2020.12.5)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.26.4)\n",
      "Requirement already satisfied: chardet<5,>=3.0.2 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (4.0.0)\n",
      "Requirement already satisfied: idna<3,>=2.5 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.10)\n",
      "Collecting httplib2>=0.9.1\n",
      "  Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)\n",
      "\u001b[K     |████████████████████████████████| 96 kB 6.9 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from httplib2>=0.9.1->oauth2client) (2.4.7)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from pandas) (2.8.1)\n",
      "Requirement already satisfied: pytz>=2017.3 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from pandas) (2021.1)\n",
      "Requirement already satisfied: numpy>=1.16.5 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from pandas) (1.20.1)\n",
      "Collecting blinker<2,>=1.0.0\n",
      "  Downloading blinker-1.8.2-py3-none-any.whl (9.5 kB)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from streamlit) (8.2.0)\n",
      "Requirement already satisfied: packaging<25,>=20 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from streamlit) (20.9)\n",
      "Collecting requests>=2.0.0\n",
      "  Downloading requests-2.32.4-py3-none-any.whl (64 kB)\n",
      "\u001b[K     |████████████████████████████████| 64 kB 11.1 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting gitpython!=3.1.19,<4,>=3.0.7\n",
      "  Downloading GitPython-3.1.44-py3-none-any.whl (207 kB)\n",
      "\u001b[K     |████████████████████████████████| 207 kB 15.3 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting altair<6,>=4.0\n",
      "  Downloading altair-5.4.1-py3-none-any.whl (658 kB)\n",
      "\u001b[K     |████████████████████████████████| 658 kB 26.0 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting rich<14,>=10.14.0\n",
      "  Downloading rich-13.9.4-py3-none-any.whl (242 kB)\n",
      "\u001b[K     |████████████████████████████████| 242 kB 24.7 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: tornado<7,>=6.0.3 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from streamlit) (6.1)\n",
      "Collecting typing-extensions<5,>=4.3.0\n",
      "  Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)\n",
      "\u001b[K     |████████████████████████████████| 45 kB 13.7 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: protobuf<6,>=3.20 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from streamlit) (3.20.0)\n",
      "Collecting tenacity<10,>=8.1.0\n",
      "  Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)\n",
      "Collecting pandas\n",
      "  Downloading pandas-2.0.3-cp38-cp38-macosx_10_9_x86_64.whl (11.7 MB)\n",
      "\u001b[K     |████████████████████████████████| 11.7 MB 16.8 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting pyarrow>=7.0\n",
      "  Downloading pyarrow-17.0.0-cp38-cp38-macosx_10_15_x86_64.whl (29.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 29.0 MB 33.4 MB/s eta 0:00:01     |██████████████████▋             | 16.8 MB 20.0 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting pydeck<1,>=0.8.0b4\n",
      "  Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
      "\u001b[K     |████████████████████████████████| 6.9 MB 18.8 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: toml<2,>=0.10.1 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: click<9,>=7.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from streamlit) (7.1.2)\n",
      "Collecting python-dateutil>=2.7.3\n",
      "  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)\n",
      "\u001b[K     |████████████████████████████████| 229 kB 19.6 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting tzdata>=2022.1\n",
      "  Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)\n",
      "\u001b[K     |████████████████████████████████| 347 kB 19.3 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting numpy>=1.16.5\n",
      "  Downloading numpy-1.24.4-cp38-cp38-macosx_10_9_x86_64.whl (19.8 MB)\n",
      "\u001b[K     |████████████████████████████████| 19.8 MB 1.3 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: jsonschema>=3.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from altair<6,>=4.0->streamlit) (3.2.0)\n",
      "Requirement already satisfied: jinja2 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from altair<6,>=4.0->streamlit) (2.11.3)\n",
      "Collecting narwhals>=1.5.2\n",
      "  Downloading narwhals-1.42.1-py3-none-any.whl (359 kB)\n",
      "\u001b[K     |████████████████████████████████| 359 kB 27.5 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting gitdb<5,>=4.0.1\n",
      "  Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)\n",
      "\u001b[K     |████████████████████████████████| 62 kB 4.2 MB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting smmap<6,>=3.0.1\n",
      "  Downloading smmap-5.0.2-py3-none-any.whl (24 kB)\n",
      "Requirement already satisfied: pyrsistent>=0.14.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.17.3)\n",
      "Requirement already satisfied: setuptools in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (52.0.0.post20210125)\n",
      "Requirement already satisfied: attrs>=17.4.0 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (20.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages (from jinja2->altair<6,>=4.0->streamlit) (1.1.1)\n",
      "Collecting charset_normalizer<4,>=2\n",
      "  Downloading charset_normalizer-3.4.2-cp38-cp38-macosx_10_9_universal2.whl (198 kB)\n",
      "\u001b[K     |████████████████████████████████| 198 kB 25.9 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting markdown-it-py>=2.2.0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)\n",
      "\u001b[K     |████████████████████████████████| 87 kB 18.2 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting pygments<3.0.0,>=2.13.0\n",
      "  Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.2 MB 3.8 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting mdurl~=0.1\n",
      "  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)\n",
      "Installing collected packages: charset-normalizer, smmap, requests, mdurl, tzdata, typing-extensions, python-dateutil, pygments, numpy, narwhals, markdown-it-py, gitdb, tenacity, rich, pydeck, pyarrow, pandas, httplib2, gitpython, blinker, altair, streamlit, oauth2client, gspread\n",
      "  Attempting uninstall: requests\n",
      "    Found existing installation: requests 2.25.1\n",
      "    Uninstalling requests-2.25.1:\n",
      "      Successfully uninstalled requests-2.25.1\n",
      "  Attempting uninstall: typing-extensions\n",
      "    Found existing installation: typing-extensions 3.7.4.3\n",
      "    Uninstalling typing-extensions-3.7.4.3:\n",
      "      Successfully uninstalled typing-extensions-3.7.4.3\n",
      "  Attempting uninstall: python-dateutil\n",
      "    Found existing installation: python-dateutil 2.8.1\n",
      "    Uninstalling python-dateutil-2.8.1:\n",
      "      Successfully uninstalled python-dateutil-2.8.1\n",
      "  Attempting uninstall: pygments\n",
      "    Found existing installation: Pygments 2.8.1\n",
      "    Uninstalling Pygments-2.8.1:\n",
      "      Successfully uninstalled Pygments-2.8.1\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.20.1\n",
      "    Uninstalling numpy-1.20.1:\n",
      "      Successfully uninstalled numpy-1.20.1\n",
      "  Attempting uninstall: tenacity\n",
      "    Found existing installation: tenacity 8.0.1\n",
      "    Uninstalling tenacity-8.0.1:\n",
      "      Successfully uninstalled tenacity-8.0.1\n",
      "  Attempting uninstall: pandas\n",
      "    Found existing installation: pandas 1.2.4\n",
      "    Uninstalling pandas-1.2.4:\n",
      "      Successfully uninstalled pandas-1.2.4\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "spyder 4.2.5 requires pyqt5<5.13, which is not installed.\n",
      "spyder 4.2.5 requires pyqtwebengine<5.13, which is not installed.\n",
      "conda-repo-cli 1.0.4 requires pathlib, which is not installed.\n",
      "anaconda-project 0.9.1 requires ruamel-yaml, which is not installed.\n",
      "scipy 1.6.2 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.4 which is incompatible.\u001b[0m\n",
      "Successfully installed altair-5.4.1 blinker-1.8.2 charset-normalizer-3.4.2 gitdb-4.0.12 gitpython-3.1.44 gspread-6.2.1 httplib2-0.22.0 markdown-it-py-3.0.0 mdurl-0.1.2 narwhals-1.42.1 numpy-1.24.4 oauth2client-4.1.3 pandas-2.0.3 pyarrow-17.0.0 pydeck-0.9.1 pygments-2.19.2 python-dateutil-2.9.0.post0 requests-2.32.4 rich-13.9.4 smmap-5.0.2 streamlit-1.40.1 tenacity-9.0.0 typing-extensions-4.13.2 tzdata-2025.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install gspread oauth2client streamlit pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1562c016",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-28 17:38:40.096 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-06-28 17:38:40.097 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:40.262 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /Users/hyunjin/opt/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-06-28 17:38:40.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:40.264 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:40.264 No runtime found, using MemoryCacheStorageManager\n",
      "2025-06-28 17:38:40.766 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:40.768 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.362 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.366 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.368 Session state does not function when running a script without `streamlit run`\n",
      "2025-06-28 17:38:41.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.373 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-28 17:38:41.376 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import streamlit as st\n",
    "\n",
    "# 구글 스프레드시트 CSV 주소 (본인의 주소로 바꿔주세요)\n",
    "url = 'https://docs.google.com/spreadsheets/d/1Aq5cikYP1BKwdL9HarO9CpCra-zksGO3o3QKnhHtGFg/export?format=csv'\n",
    "\n",
    "# 데이터 불러오기\n",
    "@st.cache_data(ttl=60)  # 60초 캐시 (데이터 실시간에 가깝게 갱신)\n",
    "def load_data():\n",
    "    df = pd.read_csv(url)\n",
    "    return df\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "# Streamlit 앱 제목\n",
    "st.title('📱 Grocery Price Tracker')\n",
    "\n",
    "# 품목 또는 세부로 검색\n",
    "search_mode = st.radio('검색 기준을 선택하세요', ['품목', '세부'])\n",
    "query = st.text_input(f'{search_mode} 입력')\n",
    "\n",
    "# 필터링\n",
    "if query:\n",
    "    if search_mode == '품목':\n",
    "        filtered_df = df[df['품목'].str.contains(query, case=False, na=False)]\n",
    "    else:\n",
    "        filtered_df = df[df['세부'].str.contains(query, case=False, na=False)]\n",
    "\n",
    "    if not filtered_df.empty:\n",
    "        # 날짜가 있는 경우 정렬\n",
    "        if '날짜' in filtered_df.columns:\n",
    "            try:\n",
    "                filtered_df['날짜'] = pd.to_datetime(filtered_df['날짜'], errors='coerce')\n",
    "                filtered_df = filtered_df.sort_values(by='날짜')\n",
    "            except Exception:\n",
    "                pass\n",
    "\n",
    "        st.write(f'🔍 {query} 구매 내역')\n",
    "        st.dataframe(filtered_df)\n",
    "\n",
    "        # 가격 추이 그래프\n",
    "        if '날짜' in filtered_df.columns and '단가(100 g, ml당)' in filtered_df.columns:\n",
    "            try:\n",
    "                import altair as alt\n",
    "                chart = alt.Chart(filtered_df).mark_line(point=True).encode(\n",
    "                    x='날짜:T',\n",
    "                    y=alt.Y('단가(100 g, ml당)', title='단가 (100 g/ml 당)'),\n",
    "                    color='마트'\n",
    "                ).properties(title=f'{query} 가격 추이')\n",
    "\n",
    "                st.altair_chart(chart, use_container_width=True)\n",
    "            except Exception:\n",
    "                st.write('📊 그래프를 표시할 수 없습니다.')\n",
    "    else:\n",
    "        st.warning('검색 결과가 없습니다. 다른 검색어를 입력해보세요.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f193561",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
